export const sectionNavigationLinks =
    document.getElementById('navigation-links')
export const appleTvSection = document.getElementById('apple-tv')
export const imageCarousel = document.getElementById('image-carousel')
export const buttonPrevImage = document.getElementById('button-prev-image')
export const buttonNextImage = document.getElementById('button-next-image')
export const dotNavigation = document.getElementById('dot-navigation')
export const hamburgerMenu = document.getElementById('hamburger-menu')
export const hamburgerMenuCheckbox = document.getElementById(
    'hamburger-menu-status'
)
export const flyoutContainer = document.getElementById('flyout-container')
export const flyoutMobile = document.getElementById('flyout-mobile')
export const header = document.getElementById('header')
export const navbar = document.getElementById('navbar')
export const flyoutShoppingbag = document.getElementById('flyout-shoppingbag')
export const shoppingbagIcon = document.getElementById('shoppingbag')
export const searchIcon = document.getElementById('search')
export const flyoutSearch = document.getElementById('flyout-search')
export const flyoutSearchInput = document.getElementById('flyout-search-input')
